name: bde_sig
services:
  dbgis:
    image: postgis/postgis
    container_name: postgis_cnt
    restart: unless-stopped
    ports: 
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - postgres_network
      
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_cnt
    restart: unless-stopped
    depends_on:
      - dbgis
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    logging:
      driver: "none"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge
    
volumes:
  pg_data:
  pgadmin_data: